### ISSUE TITLE
Feature request: Draw/specify a polygon and display only sightings within its boundaries.

### ISSUE THREAD

**Issue by mkcarr28** [hansenjohnson/WhaleMap#27]
Draw or specify (lat, lon) bounds of polygon manually to only display sightings within those boundaries. 

Ex: I only need sightings within certain bounds, but it's hard to distinguish if whales near the boundary need to be included without looking at their individual (lat, lon) (can be time-consuming)

**Comment by hansenjohnson** [comment]
Interesting idea. I've played around with the idea of adding a similar functionality with the crosstalk package. Check out the selection tool for the map/table on [their homepage](https://rstudio.github.io/crosstalk/). Would something like this be helpful?

Also, if this is something that you'll be doing very often or will become more specific, I can probably whip up a separate app for you that's dedicated to this kind of thing. I'm always wary of attempting to cram to many functionalities into a single app...

**Comment by hansenjohnson** [comment]
The more I think about this, the more I think that it's beyond the scope of this application. We can work together on this offline if you continue to have specific issues.
