### ISSUE TITLE
Feature request: daily data backups

### ISSUE THREAD

**Issue by hansenjohnson** [hansenjohnson/WhaleMap#37]
We need to get data backups up and running. Given the size of the data (small; <1 GB) I think it makes sense to do daily backups and preserve them for ~1 month. This is especially important given that a lot of input is done with Google Drive and it is relatively easy for someone to inadvertently delete data.

**Comment by hansenjohnson** [comment]
I think it makes sense to start with the cron job system. That's nice and simple and gets us up and running immediately. Who knows how long it will take us to get around to cleaning up my horrifying makefile :)

I'm going to propose storing daily backups in `/backups/WhaleMap/` (i.e., outside the WhaleMap project directory). I also think we should store an entire copy of the project, as opposed to just the data, because why not? I've created the backup dir above and added the following line to the crontab:

```
28 16 * * * rsync -qrt --delete srv/shiny-server/WhaleMap/ /backup/WhaleMap/`date +%d`
```
We can change the time of the backup (currently daily at 16:28), but I wanted to do it soon so I could see how it does.

One other thing to mention is that `rclone` has a nice backup feature. Every time a file is changed on the remote repository, `rclone` will copy the server version to `data/raw/backups` before overwriting or deleting. This at least helps avoid the situation you describe where a file is added and then accidentally zeroed between daily backups.

Should we close, or keep this open in hopes of eventually doing better with the makefile?

**Comment by draker42** [comment]
Your Makefile isn't close to horrifying; it just needs a bit of tidying!

I made a mistake; forgot the leading '/' in the rsync source path. Github let me edit your comment to add it in. Fixed in cron also. 

Note, you've decided to rsync the entire WhaleMap dir, not just WhaleMap/data. This means you're also backing up the WhaleMap/.git directory, which is an extra ~120MB per day and not terribly useful. 
We could exclude it:
```
28 16 * * * rsync -qrt --delete /srv/shiny-server/WhaleMap/ --exclude .git /backup/WhaleMap/`date +%d`
```
Note, to test replace the '-q' option with '-vn' to get a Verbose listing of what rsync is Not doing ('n' means dry-run). 

~600 MB times 30 days is an extra 20 GB of space; I have increased the guest OS' disk space from 10 to 30 GB. 

Suggest leaving this open a few days to confirm it's doing what we want. Makefile will deserve a new issue perhaps.

**Comment by hansenjohnson** [comment]
I got excited to close! But I agree, best to leave open and monitor for a time.

Both of us had to make edits to my comment. I also think we need single quotes to specify date in the folder name (`'+%d'`), no?

On second thought, we only need to back up the data because everything else is on github. Silly me. I'll change that too.

So here's the final crontab line:
```
58 2 * * * rsync -qrt --delete /srv/shiny-server/WhaleMap/data /home/hansen/backup/WhaleMap/`date '+%d'`
```

**Comment by draker42** [comment]
Looks good. 

Note you will get:
`~hansen/backups/WhaleMap/04/data/<stuff>`

If you put a trailing slash on the src `data/` in the rsync command, you will get:
`~hansen/backups/WhaleMap/04/<stuff>`

Doesn't matter, but basically the rsync rule is that if you have a trailing slash on your src/ directory, you will transfer the contents to the destination, while if you don't have a trailing slash, you will transfer the directory itself. 

No, you don't need the quotes, but they don't hurt. 
Example: `rm '-f' /tmp/hansen.txt`

In shell, use "double quotes" to escape a space or newline, etc. You can also escape it directly with a backslash. Use 'single quotes' to prevent ordinary shell expansion:
```
~$ for var in $SHELL $HOME;do echo It is: $var;done  # nothing, 2 vars, twice through the loop
It is: /bin/bash
It is: /home/daniel

~$ for var in "$SHELL $HOME";do echo It is: $var;done  # double quotes, once through the loop
It is: /bin/bash /home/daniel

~$ for var in $SHELL" "$HOME;do echo It is: $var;done  # quotes can be anywhere so long as around the space
It is: /bin/bash /home/daniel

~$ for var in $SHELL\ $HOME;do echo It is: $var;done  # backslash
It is: /bin/bash /home/daniel

~$ for var in '$SHELL $HOME';do echo It is: $var;done  # single quotes, no shell expansion
It is: $SHELL $HOME

~$ for var in '$SHELL' '$HOME';do echo It is: $var;done  # single quotes, not around the space
It is: $SHELL
It is: $HOME
```

**Comment by draker42** [comment]
I made another mistake: '%' character must be escaped in cron. So the line should become:

```
58 2 * * * rsync -qrt --delete /srv/shiny-server/WhaleMap/data /backup/WhaleMap/`date +\%d`
```
Probably better to put the whole line in a shell script, and reference that from cron instead. 

Another possibility suggested on stackexchange is to set a cron variable:
```
DATEVAR=date +%d
58 2 * * * rsync -qrt --delete /srv/shiny-server/WhaleMap/data /backup/WhaleMap/$($DATEVAR)
```

I haven't tested this.

**Comment by hansenjohnson** [comment]
I just checked the `/home/hansen/backup/` folder and it has a backup from early this morning (`07`), so it looks like your edit worked as it should. That's good news! Let's continue to monitor for another few days, and consider porting to a shell script.

**Comment by hansenjohnson** [comment]
Closing as this has been functioning well for almost a year (!)
