### ISSUE TITLE
Feature request: French translation

### ISSUE THREAD

**Issue by draker42** [hansenjohnson/WhaleMap#41]
French translation requested by CTT. 
* [ ] learn shiny i18n mechanism
* [ ] actual translation of terms to French

**Comment by hansenjohnson** [comment]
I implemented a temporary band-aid solution by embedding Google Translate in the `ui.R`. I'll need to revisit this in more detail later on, but at least there is an attempt at a fix for now...

**Comment by hansenjohnson** [comment]
I'm closing this now as I don't foresee having the development bandwidth to build a stand-alone French translation in the near future. Most of the essential information is available on the DFO static map:

http://www.dfo-mpo.gc.ca/species-especes/mammals-mammiferes/narightwhale-baleinenoirean/alert-alerte/index-fra.html
