### ISSUE TITLE
Issue: app does not load to show most recent date(s)

### ISSUE THREAD

**Issue by hansenjohnson** [hansenjohnson/WhaleMap#42]
Right now (06 May), the app opens with the date slider set to show dates between 04 April and 04 May. This is not right - it *should* be showing the last 30 days from **today**.

I have noticed this behaviour before. It's definitely not an issue with the server clock. I'm not sure what causes it. In the past my workaround has been to restart the shiny server (`sudo systemctl restart shiny-server`), which solves the issue but is pretty unsatisfying. I'm sure there's a better way.

**Comment by draker42** [comment]
The current shiny server process **and** the the current WhaleMap shiny process are both dated May 4th. So upon startup, some date field is initialized which sets the slider parameters. It would be necessary to check the date when a client connects, or just 'every X hours' and update, I guess.

**Comment by hansenjohnson** [comment]
I still don't know why the shiny process would have a different sense of time than the parent server. Perhaps a workaround is to have the date sliders reference the parent server clock as opposed to the shiny server clock.

So instead of calling `Sys.Date()` to get the date, I just made the change to grab the date via system call to the parent server:
```
# get date from server
timeNow = as.Date(system('date \'+%Y-%m-%d\'', intern = TRUE))
```
Not necessarily pretty, but hopefully it does the job. I'll wait before closing to see how it works, or if there are other suggestions

**Comment by draker42** [comment]
That is pretty ugly, because every time you call 'system()' the OS has to do a fork() and exec(), which is costly in terms of resource usage. 
I'm out of my depth on this, better ask Dean. But if I had to guess, something is getting cached. 
I found this: http://shiny.rstudio.com/gallery/current-time.html
but upon reflection I think it's invalidating the output field in the UI, not the actual Sys.Date(). 
This behaviour is so bizarre, you must be doing something wrong (likely trivial)...

**Comment by hansenjohnson** [comment]
Oops, well thanks for the clarification.

I think I know what I' doing wrong. The correct 'shiny' way to dynamically render a user-input element is to build it in `server.R` and then pass it back to the `ui.R`. That way the ui element is rebuilt each time the app starts, and *should* have the correct time. It's exactly what I'm already doing for the year input, so it should be trivial to implement. I'll get on that now.

**Comment by hansenjohnson** [comment]
I realize that the system call would not have worked anyway because the `ui.R` script is not executed for every new shiny session. I've just implemented what I described above, so we'll see how it works.

**Comment by hansenjohnson** [comment]
I've seen this work reliably for several tests on mobile and desktop using different browser types. I'm content to close and re-open if the issue crops up again.
