### ISSUE TITLE
Feature request: unique shiny server instance identifier

### ISSUE THREAD

**Issue by draker42** [hansenjohnson/WhaleMap#43]
If we implement load balancing across multiple shiny processes, it would be helpful for debugging if we could glance at the page and know **which** shiny server we were actually looking at. This would easily help confirm load balancing was working, and to quickly identify instances that are misbehaving in some way. 

Additionally, we could ask users to include the ID of the shiny instance when submitting bug reports (especially if the problem seems 'intermittent'). 

This should be unobstrusive, almost un-noticeable to users, but still visible if a user takes a screen shot. Perhaps just a single code somewhere in a corner (A1, B1, A2, B2, etc.)

**Comment by hansenjohnson** [comment]
I think that's a good idea. Do you have any thoughts about how to make shiny aware of its instance identity? My first thought would be to use `system(x, intern=TRUE)`, where x is the terminal command used to determine the instance ID. The `intern` argument tells R to not only execute the system command, but read the output into memory. I just figured this out with #42

**Comment by draker42** [comment]
I would just hard-code a value into some R-accessible file, and document it as part of the setup routine. (`WhaleMap.conf` file? :)

**Comment by hansenjohnson** [comment]
That makes a lot more sense - I'm getting trigger happy with these system calls :)

**Comment by draker42** [comment]
So I started by just putting in a hard-coded value as a server tag: '1' for goldone, '2' for goldtwo, etc. 

But now I'm running multiple shinies on each node. They are running off the **same** site_dir so the code is identical for each instance on the same node. The only differences are in the shiny-server.conf file, specifying a unique logging directory and server port. 

So I thought 'servername:port' would be an identifier, but I can't find a way to display that. I made a new reactive variable (?) in `server.R`:
```
  # server info tag
  output$serverTag <- renderText({
    paste(sep = ":",
      session$clientData$url_hostname,
      toString(session$clientData$url_port, width=0),
      session$request$HTTP_HOST # for example
    )
  })
```
This works, except the it's the wrong hostname, and 'url_port' is blank (and so are most of the HTTP headers I tried). Here's `ui.R`:
```
notificationItem(textOutput("serverTag"),
                             icon = icon("tag"),
                             href = "#")
```
I installed this [gist](https://gist.github.com/trestletech/7255596) on [our server](https://whalemap.ocean.dal.ca/headers/) in order to examine all the available HTTP headers, but could not find anything useful to display. 

In theory I could set a custom HTTP header in the Apache configuration that specified which back-end server to which we are reverse proxying. To test, I set a static custom header with my name in it. This shows up just fine when I reverse proxy to a perl script that [prints all headers](https://whalemap.ocean.dal.ca/hdrs), but the headers here do not match [the shiny header inspector]([https://whalemap.ocean.dal.ca/headers)! Why?

Probably gone down the wrong rabbit hole trying to parse HTTP headers. Is there a different way to get the server port of the currently running shiny?

**Comment by draker42** [comment]
So in the end I've accomplished this by running every instance of shiny with it's own userid (no more running as root) and setting a custom environment variable in `~<userid>/.Renviron`, e.g.:
`R_SHNYSRVINST=GoldOneA`

Then in `ui.R`:
```
  notificationItem(Sys.getenv("R_SHNYSRVINST"),
                   icon = icon("tag"),
                   href = "#")
```
