### ISSUE TITLE
Feature request: indicate when map is loading / finished loading

### ISSUE THREAD

**Issue by hansenjohnson** [hansenjohnson/WhaleMap#45]
It would be very good to have a little spinning loading icon to indicate to users when the map is finished updating after they click 'Go'. This is particularly important as we pick up more users and our server potentially starts to slow down. I know @daattali has done this in a few different [ways](https://deanattali.com/blog/advanced-shiny-tips/), but I'm not sure which is most appropriate here.

**Comment by daattali** [comment]
If the bulk of the waiting time is because of server-side processing, yes we can do that. If the load time is more client side (the map itself takes time to render) it'll be a lot trickier.
